DELETE FROM TB_Pendaftaran
DBCC CHECKIDENT ('TB_Pendaftaran', RESEED, 0);

DELETE FROM TB_Vaksinasi
DBCC CHECKIDENT ('TB_Vaksinasi', RESEED, 0);

DELETE FROM TB_Validasi
DBCC CHECKIDENT ('TB_Validasi', RESEED, 0);

DELETE FROM TB_DataKesehatan
DBCC CHECKIDENT ('TB_DataKesehatan', RESEED, 0);

DELETE FROM TB_Penduduk

DELETE FROM TB_Admin
DBCC CHECKIDENT ('TB_Admin', RESEED, 0);

DELETE FROM TB_Petugas
DBCC CHECKIDENT ('TB_Petugas', RESEED, 0);

DELETE FROM TB_Pimpinan
DBCC CHECKIDENT ('TB_Pimpinan', RESEED, 0);


DELETE FROM TB_Faskes
DBCC CHECKIDENT ('TB_Faskes', RESEED, 0);

DELETE FROM TB_Alamat
DBCC CHECKIDENT ('TB_Alamat', RESEED, 0);

DELETE FROM TB_AlamatFaskes
DBCC CHECKIDENT ('TB_AlamatFaskes', RESEED, 0);

DELETE FROM TB_Kota
DBCC CHECKIDENT ('TB_Kota', RESEED, 0);

DELETE FROM TB_Provinsi
DBCC CHECKIDENT ('TB_Provinsi', RESEED, 0);

