USE [master]
GO

/****** Object:  Table [dbo].[TB_Alamat]    Script Date: 22/06/2021 20:05:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_Alamat](
	[idAlamat] [int] IDENTITY(1,1) NOT NULL,
	[namaAlamat] [varchar](50) NOT NULL,
	[fk_idKota] [int] NOT NULL,
 CONSTRAINT [PK_TB_Alamat] PRIMARY KEY CLUSTERED 
(
	[idAlamat] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_Alamat]  WITH CHECK ADD  CONSTRAINT [FK_TB_Alamat_idKota] FOREIGN KEY([fk_idKota])
REFERENCES [dbo].[TB_Kota] ([idKota])
GO

ALTER TABLE [dbo].[TB_Alamat] CHECK CONSTRAINT [FK_TB_Alamat_idKota]
GO

