USE [master]
GO

/****** Object:  Table [dbo].[TB_Provinsi]    Script Date: 22/06/2021 20:07:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_Provinsi](
	[idProvinsi] [int] IDENTITY(1,1) NOT NULL,
	[namaProvinsi] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_Provinsi] PRIMARY KEY CLUSTERED 
(
	[idProvinsi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

